---
roles:
    - src: robertdebock.java
      version: "4.2.0"

    - src: gantsign.golang
      version: "2.10.2"

    - src: geerlingguy.docker
      version: "7.1.0"

    - src: nvidia.nvidia_driver
      version: "v2.3.0"
