---
- name: All
  hosts: all
  become: true
  become_user: root
  roles:
      - hosts
      - slurm-common

- name: Login and controller
  hosts: slurm_master
  become: true
  become_user: root
  roles:
      - geerlingguy.docker
      - prometheus-node-exporter
      - prometheus-slurm-exporter
      - slurm-master
      - prometheus
      - grafana
      - alertmanager
      - rsyslog_server

- name: Worker
  hosts: slurm_worker
  become: true
  become_user: root
  roles:
      - prometheus-node-exporter
      - prometheus-slurm-exporter
      - slurm-worker
      - rsyslog_client
