---
- name: Common set up
  hosts: all
  become: true
  become_user: root
  roles:
    - hosts
    - slurm-common

- name: Slurm master
  hosts: slurm_master
  become: true
  become_user: root
  roles:
    - slurm-master
  tasks:
    - service:
        name=slurmctld
        state=restarted
    - service:
        name=slurmdbd
        state=restarted

- name: Slurm worker
  hosts: slurm_worker
  become: true
  become_user: root
  roles:
    - slurm-worker
  tasks:
    - service:
        name=slurmd
        state=restarted