---
- name: Install MUNGE dependencies
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - libmunge-dev
      - munge

- name: Set correct permissions for munge key
  file:
      path: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: "0400"

- name: Configure MUNGE
  copy: src=etc/munge/munge.key
      dest=/etc/munge/munge.key
      owner=munge
      group=munge
      mode=0400

- name: Start and Enable Munge Service
  systemd:
      name: munge
      state: started
      enabled: yes
