---
- name: Add cgroups to grub options to control cpus and memory
  lineinfile:
      dest: /etc/default/grub
      insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
      line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub
  block:
      - name: update grub
        command: update-grub
        register: update_grub_cmd
        changed_when: update_grub_cmd.rc == 0
      - name: reboot after updating grub config
        reboot:
            reboot_timeout: "{{ slurm_node_reboot_timeout }}"

  when: update_grub.changed and ansible_os_family == "Debian"
- name: Deploy SLURM cgroup configuration file (main)
  copy:
      src: "etc/slurm/cgroup.conf"
      dest: "/etc/slurm/cgroup.conf"
      mode: 0444
      owner: root
      group: root

- name: Ensure slurmd daemon is up
  service:
      name: slurmd
      enabled: yes
      state: restarted
